apiVersion: v1
kind: Service
metadata:
  name: lab-api-service
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31234
  selector:
    app: lab-api

#  ports:
#    - protocol: TCP
#      port: 8080
#      targetPort: 3000
#      nodePort: 31234
      